language: php
php:
    - 7.0
    - 7.1
    - nightly
before_script: composer install --prefer-source
script: phpunit --coverage-clover=coverage.clover
after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
notifications:
    slack: innmind:nAiLaAi6RU4wGEAdL6FuKdyF
